### PR TITLE
support android

### PR DESCRIPTION
**Pull request by XuHaoJun**

### CODE REVIEW

**Comment by NiklasEi** [comment]
Hey, thank you.
Could you outline how I can test this on Android? I have very little experience with Bevy on mobile platforms.

**Comment by XuHaoJun** [comment]
You can run `cargo apk run -p bevy_mobile_example` for android test in bevy repo.

Android Build & Run docs:
https://github.com/bevyengine/bevy/tree/main/examples#android

**Comment by NiklasEi** [comment]
Can you run the template on Android with only this change?
I run into some issues and as far as I understand there are a few more changes needed. For example, we will have to build a `cdylib` and use the `#[bevy_main]` macro to get some boilerplate setup for android and iOS.

**Comment by NiklasEi** [comment]
I've spend some more time with Bevy and Android recently and got it to work with a couple more changes in this template (see [android_support](https://github.com/NiklasEi/bevy_game_template/tree/android_support)). I would prefer if we don't need to add a new direct dependency, but enable the shared library through the cpal feature on the dependency using cpal (kira). I am trying to add a corresponding feature to kira in tesselode/kira#51.

**Comment by NiklasEi** [comment]
Closing in favor of #60

**Pull request closed without merging**
